### ISSUE TITLE
How do we use region files?

### ISSUE THREAD

**Issue by aerarslan** [HakkaTjakka/SKULL-MAZE#1]
Hey, I love your work. How exactly do we use region files to create worlds? I am very far away from the idea and never done it.

**Comment by Simon946** [comment]
You can make a minecraft 1.12.2 world using the create new world option in minecraft.

![create new world](https://user-images.githubusercontent.com/56819218/108409917-11089c00-7227-11eb-951e-4e669a0a6e49.PNG)



 Then, you go to AppData\Roaming\.minecraft\saves and open the folder of your created world. 

to open the correct folder, press the windows key + R. type in the searchbar 'appdata' and hit enter. From there, navigate to Roaming\.minecraft\saves and open the folder of your created world.



There, you will find the region folder. Then you can replace all the .mca files with the region files of the skull maze.
When that is done, you can open the world using minecraft.

**Comment by aerarslan** [comment]
Thank you for your answer, it is awesome and detailed. I did the things you have said while I was trying to find how to use these files but when I join my world, I could not see the new regions. Maybe I respawned somewhere else or in the wrong region? How do I spawn in these regions or find them?

**Comment by Simon946** [comment]
It is correct that you can't find the world because the 0.0.mca file is missing. try teleporting to: 14336 ~ 11264

**Comment by aerarslan** [comment]
Thank you, you are awesome!! How can I understand where to go when I use a region file in my world?

**Comment by Simon946** [comment]
Each region is 512 blocks long and 512 blocks wide. The name of the region is their relative position. For example r.0.2 is 1 region above r.0.1 If you want to go to the blocks in region r.5.4.mca you teleport to x= 5*512 y= between 0 and 255 z= 4*512

**Comment by aerarslan** [comment]
I understand it thank you, you are awesome !!!

**Comment by HakkaTjakka** [comment]
Yes, correct. Little correction: When you have region file r.0.1.mca, its south of  r.0.0.mca, so r.0.1.mca is above or  north of r.0.2. Then you match the north/south directions in MC. If you want to go to the center of the skull maze thing its arround r.20.20.mca, so /tp 10240 ~ 10240 brings you there.
Note, i'm uploading right now a newer version of skull maze, trying to get the rails between separate connected together, its not working perfect but i'm working on that. 
The newer files overwrite the older in the repo.

**Comment by HakkaTjakka** [comment]
https://www.facebook.com/groups/360586528705710/permalink/417803772983985/
